//Autogenerated by BlazorBoilerplate.EntityGenerator
using BlazorBoilerplate.Constants;
using System;
using System.Collections.Generic;
using System.ComponentModel;

namespace BlazorBoilerplate.Shared.DataInterfaces
{
    public interface IApplicationUser
    {
        string TenantId { get; set; }

        String FirstName { get; set; }

        String LastName { get; set; }

        String FullName { get; set; }

        String PasswordHash { get; set; }

        String SecurityStamp { get; set; }

        ICollection<IApplicationUserRole> UserRoles { get; }

        ICollection<IApiLogItem> ApiLogItems { get; }

        IUserProfile Profile { get; set; }

        ICollection<IMessage> Messages { get; }

        Guid Id { get; set; }

        String UserName { get; set; }

        String NormalizedUserName { get; set; }

        String Email { get; set; }

        String NormalizedEmail { get; set; }

        Boolean EmailConfirmed { get; set; }

        String ConcurrencyStamp { get; set; }

        String PhoneNumber { get; set; }

        Boolean PhoneNumberConfirmed { get; set; }

        Boolean TwoFactorEnabled { get; set; }

        DateTimeOffset? LockoutEnd { get; set; }

        Boolean LockoutEnabled { get; set; }

        Int32 AccessFailedCount { get; set; }

    }
}
