//Autogenerated by BlazorBoilerplate.EntityGenerator
using BlazorBoilerplate.Constants;
using System;
using System.Collections.Generic;
using System.ComponentModel;

namespace BlazorBoilerplate.Shared.DataInterfaces
{
    public interface ILocalizationRecord
    {
        Int64 Id { get; set; }

        String MsgId { get; set; }

        String MsgIdPlural { get; set; }

        String Translation { get; set; }

        String Culture { get; set; }

        String ContextId { get; set; }

        ICollection<IPluralTranslation> PluralTranslations { get; }

    }
}
