//Autogenerated by BlazorBoilerplate.EntityGenerator
using BlazorBoilerplate.Constants;
using System;
using System.Collections.Generic;
using System.ComponentModel;

namespace BlazorBoilerplate.Shared.DataInterfaces
{
    public interface IMessage
    {
        Int32 Id { get; set; }

        String UserName { get; set; }

        String Text { get; set; }

        DateTime When { get; set; }

        Guid UserID { get; set; }

        IApplicationUser Sender { get; set; }

    }
}
