//Autogenerated by BlazorBoilerplate.EntityGenerator
using BlazorBoilerplate.Constants;
using System;
using System.Collections.Generic;
using System.ComponentModel;

namespace BlazorBoilerplate.Shared.DataInterfaces
{
    public interface IPluralFormRule
    {
        String Language { get; set; }

        Int32 Count { get; set; }

        String Selector { get; set; }

    }
}
