//Autogenerated by BlazorBoilerplate.EntityGenerator
using BlazorBoilerplate.Constants;
using System;
using System.Collections.Generic;
using System.ComponentModel;

namespace BlazorBoilerplate.Shared.DataInterfaces
{
    public interface IQueuedEmail
    {
        Int64 Id { get; set; }

        String Email { get; set; }

        EmailType EmailType { get; set; }

        DateTime CreatedOn { get; set; }

        DateTime? SentOn { get; set; }

    }
}
