using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BlazorBoilerplate.Shared.Dto.Ontology
{
    public class GetCompatibleAutoMlSolutionsRequestDto
    {
        public Dictionary<string, string> Configuration { get; set; } //auto property
        //get and set method will be generated by compiler
    }
}
