//Autogenerated by BlazorBoilerplate.EntityGenerator
using BlazorBoilerplate.Constants;
using BlazorBoilerplate.Shared.DataInterfaces;
using Breeze.Sharp;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;

namespace BlazorBoilerplate.Shared.Dto.Db
{
    public partial class ApplicationRole : BaseEntity, IApplicationRole
    {
        public String TenantId
        {
            get { return GetValue<String>(); }
            set { SetValue(value); }
        }

        ICollection<IApplicationUserRole> IApplicationRole.UserRoles { get => UserRoles.Select(i => (IApplicationUserRole)i).ToList(); }

        public NavigationSet<ApplicationUserRole> UserRoles
        {
            get { return GetValue<NavigationSet<ApplicationUserRole>>(); }
        }

        public Guid Id
        {
            get { return GetValue<Guid>(); }
            set { SetValue(value); }
        }

        public String Name
        {
            get { return GetValue<String>(); }
            set { SetValue(value); }
        }

        public String NormalizedName
        {
            get { return GetValue<String>(); }
            set { SetValue(value); }
        }

        public String ConcurrencyStamp
        {
            get { return GetValue<String>(); }
            set { SetValue(value); }
        }

    }
}
