//Autogenerated by BlazorBoilerplate.EntityGenerator
using BlazorBoilerplate.Constants;
using BlazorBoilerplate.Shared.DataInterfaces;
using Breeze.Sharp;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;

namespace BlazorBoilerplate.Shared.Dto.Db
{
    public partial class ApplicationUserRole : BaseEntity, IApplicationUserRole
    {
        public String TenantId
        {
            get { return GetValue<String>(); }
            set { SetValue(value); }
        }

        IApplicationUser IApplicationUserRole.User { get => User; set => User = (ApplicationUser)value; }

        public ApplicationUser User
        {
            get { return GetValue<ApplicationUser>(); }
            set { SetValue(value); }
        }

        IApplicationRole IApplicationUserRole.Role { get => Role; set => Role = (ApplicationRole)value; }

        public ApplicationRole Role
        {
            get { return GetValue<ApplicationRole>(); }
            set { SetValue(value); }
        }

        public Guid UserId
        {
            get { return GetValue<Guid>(); }
            set { SetValue(value); }
        }

        public Guid RoleId
        {
            get { return GetValue<Guid>(); }
            set { SetValue(value); }
        }

    }
}
