//Autogenerated by BlazorBoilerplate.EntityGenerator
using BlazorBoilerplate.Constants;
using BlazorBoilerplate.Shared.DataInterfaces;
using Breeze.Sharp;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;

namespace BlazorBoilerplate.Shared.Dto.Db
{
    public partial class LocalizationRecord : BaseEntity, ILocalizationRecord
    {
        public Int64 Id
        {
            get { return GetValue<Int64>(); }
            set { SetValue(value); }
        }

        public String MsgId
        {
            get { return GetValue<String>(); }
            set { SetValue(value); }
        }

        public String MsgIdPlural
        {
            get { return GetValue<String>(); }
            set { SetValue(value); }
        }

        public String Translation
        {
            get { return GetValue<String>(); }
            set { SetValue(value); }
        }

        public String Culture
        {
            get { return GetValue<String>(); }
            set { SetValue(value); }
        }

        public String ContextId
        {
            get { return GetValue<String>(); }
            set { SetValue(value); }
        }

        ICollection<IPluralTranslation> ILocalizationRecord.PluralTranslations { get => PluralTranslations.Select(i => (IPluralTranslation)i).ToList(); }

        public NavigationSet<PluralTranslation> PluralTranslations
        {
            get { return GetValue<NavigationSet<PluralTranslation>>(); }
        }

    }
}
