//Autogenerated by BlazorBoilerplate.EntityGenerator
using BlazorBoilerplate.Constants;
using BlazorBoilerplate.Shared.DataInterfaces;
using Breeze.Sharp;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;

namespace BlazorBoilerplate.Shared.Dto.Db
{
    public partial class PluralTranslation : BaseEntity, IPluralTranslation
    {
        public Int64 Id
        {
            get { return GetValue<Int64>(); }
            set { SetValue(value); }
        }

        public Int32 Index
        {
            get { return GetValue<Int32>(); }
            set { SetValue(value); }
        }

        public String Translation
        {
            get { return GetValue<String>(); }
            set { SetValue(value); }
        }

        public Int64 LocalizationRecordId
        {
            get { return GetValue<Int64>(); }
            set { SetValue(value); }
        }

        ILocalizationRecord IPluralTranslation.LocalizationRecord { get => LocalizationRecord; set => LocalizationRecord = (LocalizationRecord)value; }

        public LocalizationRecord LocalizationRecord
        {
            get { return GetValue<LocalizationRecord>(); }
            set { SetValue(value); }
        }

    }
}
