//Autogenerated by BlazorBoilerplate.EntityGenerator
using BlazorBoilerplate.Constants;
using BlazorBoilerplate.Shared.DataInterfaces;
using Breeze.Sharp;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;

namespace BlazorBoilerplate.Shared.Dto.Db
{
    public partial class QueuedEmail : BaseEntity, IQueuedEmail
    {
        public Int64 Id
        {
            get { return GetValue<Int64>(); }
            set { SetValue(value); }
        }

        public String Email
        {
            get { return GetValue<String>(); }
            set { SetValue(value); }
        }

        public EmailType EmailType
        {
            get { return GetValue<EmailType>(); }
            set { SetValue(value); }
        }

        public DateTime CreatedOn
        {
            get { return GetValue<DateTime>(); }
            set { SetValue(value); }
        }

        public DateTime? SentOn
        {
            get { return GetValue<DateTime?>(); }
            set { SetValue(value); }
        }

    }
}
