//generated by Blazor.Sharp.Generator
using Breeze.Sharp;
using System;

namespace BlazorBoilerplate.Shared.Dto.Db
{
    public partial class TenantSetting : BaseEntity
    {

        public SettingKey Key
        {
            get { return GetValue<SettingKey>(); }
            set { SetValue(value); }
        }

        public String TenantId
        {
            get { return GetValue<String>(); }
            set { SetValue(value); }
        }

        public SettingType Type
        {
            get { return GetValue<SettingType>(); }
            set { SetValue(value); }
        }

        public SettingValue? Value
        {
            get { return GetValue<SettingValue?>(); }
            set { SetValue(value); }
        }

   }
}
