apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: omamldata
  name: omamldata
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5000Mi
status: {}
