//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorBoilerplate.Localization {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorBoilerplate.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} API resources fetched.
        /// </summary>
        public static string _0__API_resources_fetched {
            get {
                return ResourceManager.GetString("{0} API resources fetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} clients fetched.
        /// </summary>
        public static string _0__clients_fetched {
            get {
                return ResourceManager.GetString("{0} clients fetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} identity resources fetched.
        /// </summary>
        public static string _0__identity_resources_fetched {
            get {
                return ResourceManager.GetString("{0} identity resources fetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} roles fetched.
        /// </summary>
        public static string _0__roles_fetched {
            get {
                return ResourceManager.GetString("{0} roles fetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} tenants fetched.
        /// </summary>
        public static string _0__tenants_fetched {
            get {
                return ResourceManager.GetString("{0} tenants fetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} users fetched.
        /// </summary>
        public static string _0__users_fetched {
            get {
                return ResourceManager.GetString("{0} users fetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Allow.
        /// </summary>
        public static string Allow {
            get {
                return ResourceManager.GetString("Allow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Already registered?.
        /// </summary>
        public static string AlreadyRegistered {
            get {
                return ResourceManager.GetString("AlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a API Resource {0} created.
        /// </summary>
        public static string API_Resource__0__created {
            get {
                return ResourceManager.GetString("API Resource {0} created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a API Resource {0} deleted.
        /// </summary>
        public static string API_Resource__0__deleted {
            get {
                return ResourceManager.GetString("API Resource {0} deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a API Resource {0} updated.
        /// </summary>
        public static string API_Resource__0__updated {
            get {
                return ResourceManager.GetString("API Resource {0} updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a OpenID API resources.
        /// </summary>
        public static string ApiResources {
            get {
                return ResourceManager.GetString("ApiResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Api Audit Log.
        /// </summary>
        public static string AppAdminNavApiAuditLog {
            get {
                return ResourceManager.GetString("AppAdminNavApiAuditLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a DB Logging Viewer.
        /// </summary>
        public static string AppAdminNavDBLoggingView {
            get {
                return ResourceManager.GetString("AppAdminNavDBLoggingView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a FrontEnd.
        /// </summary>
        public static string AppAdminNavFrontEnd {
            get {
                return ResourceManager.GetString("AppAdminNavFrontEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Monitoring.
        /// </summary>
        public static string AppAdminNavMonitoring {
            get {
                return ResourceManager.GetString("AppAdminNavMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Help &amp; Support.
        /// </summary>
        public static string AppHelpAndSupport {
            get {
                return ResourceManager.GetString("AppHelpAndSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Administration.
        /// </summary>
        public static string AppHoverAdmin {
            get {
                return ResourceManager.GetString("AppHoverAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Minimize Navigation Bar.
        /// </summary>
        public static string AppHoverNavMinimize {
            get {
                return ResourceManager.GetString("AppHoverNavMinimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Toggle Navigation Bar.
        /// </summary>
        public static string AppHoverNavToggle {
            get {
                return ResourceManager.GetString("AppHoverNavToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Blazer Boilerplate.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dashboard.
        /// </summary>
        public static string AppNavDashboard {
            get {
                return ResourceManager.GetString("AppNavDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Drag and Drop.
        /// </summary>
        public static string AppNavDragAndDrop {
            get {
                return ResourceManager.GetString("AppNavDragAndDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Email.
        /// </summary>
        public static string AppNavEmail {
            get {
                return ResourceManager.GetString("AppNavEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Features.
        /// </summary>
        public static string AppNavFeatures {
            get {
                return ResourceManager.GetString("AppNavFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Forum.
        /// </summary>
        public static string AppNavForum {
            get {
                return ResourceManager.GetString("AppNavForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Homepage.
        /// </summary>
        public static string AppNavHome {
            get {
                return ResourceManager.GetString("AppNavHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Read Email.
        /// </summary>
        public static string AppNavReadEmail {
            get {
                return ResourceManager.GetString("AppNavReadEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Screenshots.
        /// </summary>
        public static string AppNavScreenshots {
            get {
                return ResourceManager.GetString("AppNavScreenshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Send Email.
        /// </summary>
        public static string AppNavSendEmail {
            get {
                return ResourceManager.GetString("AppNavSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sponsors.
        /// </summary>
        public static string AppNavSponsors {
            get {
                return ResourceManager.GetString("AppNavSponsors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a BlazorBP.
        /// </summary>
        public static string AppShortName {
            get {
                return ResourceManager.GetString("AppShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Are you sure you want to delete &apos;{0}&apos;?.
        /// </summary>
        public static string Are_you_sure_you_want_to_delete__0__ {
            get {
                return ResourceManager.GetString("Are you sure you want to delete {0}?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Authentication required.
        /// </summary>
        public static string AuthenticationRequired {
            get {
                return ResourceManager.GetString("AuthenticationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Authenticator code.
        /// </summary>
        public static string AuthenticatorCode {
            get {
                return ResourceManager.GetString("AuthenticatorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Admin.
        /// </summary>
        public static string BreadCrumbadmin {
            get {
                return ResourceManager.GetString("BreadCrumbadmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a API Audit Log.
        /// </summary>
        public static string BreadCrumbadminapilog {
            get {
                return ResourceManager.GetString("BreadCrumbadminapilog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a API Resources.
        /// </summary>
        public static string BreadCrumbadminapiResources {
            get {
                return ResourceManager.GetString("BreadCrumbadminapiResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Clients.
        /// </summary>
        public static string BreadCrumbadminclients {
            get {
                return ResourceManager.GetString("BreadCrumbadminclients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Application Log.
        /// </summary>
        public static string BreadCrumbadmindblog {
            get {
                return ResourceManager.GetString("BreadCrumbadmindblog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Identity Resources.
        /// </summary>
        public static string BreadCrumbadminidentityResources {
            get {
                return ResourceManager.GetString("BreadCrumbadminidentityResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tenant Manager.
        /// </summary>
        public static string BreadCrumbadminmultitenancy {
            get {
                return ResourceManager.GetString("BreadCrumbadminmultitenancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Roles Manager.
        /// </summary>
        public static string BreadCrumbadminroles {
            get {
                return ResourceManager.GetString("BreadCrumbadminroles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Settings.
        /// </summary>
        public static string BreadCrumbadminsettings {
            get {
                return ResourceManager.GetString("BreadCrumbadminsettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Email Configurations.
        /// </summary>
        public static string BreadCrumbadminsettingsemail {
            get {
                return ResourceManager.GetString("BreadCrumbadminsettingsemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Users.
        /// </summary>
        public static string BreadCrumbadminusers {
            get {
                return ResourceManager.GetString("BreadCrumbadminusers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dashboard.
        /// </summary>
        public static string BreadCrumbdashboard {
            get {
                return ResourceManager.GetString("BreadCrumbdashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Drag and Drop.
        /// </summary>
        public static string BreadCrumbdrag_and_drop {
            get {
                return ResourceManager.GetString("BreadCrumbdrag_and_drop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Send Email.
        /// </summary>
        public static string BreadCrumbemail {
            get {
                return ResourceManager.GetString("BreadCrumbemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Read Email.
        /// </summary>
        public static string BreadCrumbemail_view {
            get {
                return ResourceManager.GetString("BreadCrumbemail_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Forum.
        /// </summary>
        public static string BreadCrumbforum {
            get {
                return ResourceManager.GetString("BreadCrumbforum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Home.
        /// </summary>
        public static string BreadCrumbHome {
            get {
                return ResourceManager.GetString("BreadCrumbHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Screenshots.
        /// </summary>
        public static string BreadCrumbscreenshots {
            get {
                return ResourceManager.GetString("BreadCrumbscreenshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sponsors.
        /// </summary>
        public static string BreadCrumbsponsors {
            get {
                return ResourceManager.GetString("BreadCrumbsponsors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ToDo.
        /// </summary>
        public static string BreadCrumbtodo_list {
            get {
                return ResourceManager.GetString("BreadCrumbtodo_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Browser remembered.
        /// </summary>
        public static string BrowserRemembered {
            get {
                return ResourceManager.GetString("BrowserRemembered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Change Password.
        /// </summary>
        public static string Change_Password {
            get {
                return ResourceManager.GetString("Change Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Change password for {0}.
        /// </summary>
        public static string Change_password_for__0_ {
            get {
                return ResourceManager.GetString("Change password for {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Client {0} created.
        /// </summary>
        public static string Client__0__created {
            get {
                return ResourceManager.GetString("Client {0} created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Client {0} deleted.
        /// </summary>
        public static string Client__0__deleted {
            get {
                return ResourceManager.GetString("Client {0} deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Client {0} updated.
        /// </summary>
        public static string Client__0__updated {
            get {
                return ResourceManager.GetString("Client {0} updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Optimistic concurrency failure, object has been modified..
        /// </summary>
        public static string ConcurrencyFailure {
            get {
                return ResourceManager.GetString("ConcurrencyFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Confirm Delete.
        /// </summary>
        public static string Confirm_Delete {
            get {
                return ResourceManager.GetString("Confirm Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Confirm Email.
        /// </summary>
        public static string Confirm_Email {
            get {
                return ResourceManager.GetString("Confirm Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Create a new API resource.
        /// </summary>
        public static string CreateApiResourcePermission {
            get {
                return ResourceManager.GetString("CreateApiResourcePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Create a new client.
        /// </summary>
        public static string CreateClientPermission {
            get {
                return ResourceManager.GetString("CreateClientPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Create a new identity resource.
        /// </summary>
        public static string CreateIdentityResourcePermission {
            get {
                return ResourceManager.GetString("CreateIdentityResourcePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Create a new role.
        /// </summary>
        public static string CreateRolePermission {
            get {
                return ResourceManager.GetString("CreateRolePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Create a new user.
        /// </summary>
        public static string CreateUserPermission {
            get {
                return ResourceManager.GetString("CreateUserPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Current password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a An unknown failure has occurred..
        /// </summary>
        public static string DefaultError {
            get {
                return ResourceManager.GetString("DefaultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delete any API resource.
        /// </summary>
        public static string DeleteApiResourcePermission {
            get {
                return ResourceManager.GetString("DeleteApiResourcePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delete any client.
        /// </summary>
        public static string DeleteClientPermission {
            get {
                return ResourceManager.GetString("DeleteClientPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delete any identity resource.
        /// </summary>
        public static string DeleteIdentityResourcePermission {
            get {
                return ResourceManager.GetString("DeleteIdentityResourcePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delete any role.
        /// </summary>
        public static string DeleteRolePermission {
            get {
                return ResourceManager.GetString("DeleteRolePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delete any user.
        /// </summary>
        public static string DeleteUserPermission {
            get {
                return ResourceManager.GetString("DeleteUserPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Email &apos;{0}&apos; is already taken..
        /// </summary>
        public static string DuplicateEmail {
            get {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Role name &apos;{0}&apos; is already taken..
        /// </summary>
        public static string DuplicateRoleName {
            get {
                return ResourceManager.GetString("DuplicateRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a User Name &apos;{0}&apos; is already taken..
        /// </summary>
        public static string DuplicateUserName {
            get {
                return ResourceManager.GetString("DuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Edit &apos;{0}&apos;.
        /// </summary>
        public static string Edit__0_ {
            get {
                return ResourceManager.GetString("Edit {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The {0} field is not a valid e-mail address..
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Email not confirmed.
        /// </summary>
        public static string EmailNotConfirmed {
            get {
                return ResourceManager.GetString("EmailNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Email settings.
        /// </summary>
        public static string EmailSettings {
            get {
                return ResourceManager.GetString("EmailSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Email Verification Failed.
        /// </summary>
        public static string EmailVerificationFailed {
            get {
                return ResourceManager.GetString("EmailVerificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Email Verification Successful.
        /// </summary>
        public static string EmailVerificationSuccessful {
            get {
                return ResourceManager.GetString("EmailVerificationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The {0} must be at least {2} and at max {1} characters long..
        /// </summary>
        public static string ErrorInvalidLength {
            get {
                return ResourceManager.GetString("ErrorInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The {0} field is mandatory..
        /// </summary>
        public static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Forgot your password?.
        /// </summary>
        public static string Forgot_your_password_ {
            get {
                return ResourceManager.GetString("Forgot your password?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Forgot your authenticator?.
        /// </summary>
        public static string ForgotAuthenticator {
            get {
                return ResourceManager.GetString("ForgotAuthenticator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Forgot Password Email Sent.
        /// </summary>
        public static string ForgotPasswordEmailSent {
            get {
                return ResourceManager.GetString("ForgotPasswordEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Identity Resource {0} created.
        /// </summary>
        public static string Identity_Resource__0__created {
            get {
                return ResourceManager.GetString("Identity Resource {0} created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Identity Resource {0} deleted.
        /// </summary>
        public static string Identity_Resource__0__deleted {
            get {
                return ResourceManager.GetString("Identity Resource {0} deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Identity Resource {0} updated.
        /// </summary>
        public static string Identity_Resource__0__updated {
            get {
                return ResourceManager.GetString("Identity Resource {0} updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a OpenID Identity Resources.
        /// </summary>
        public static string IdentityResources {
            get {
                return ResourceManager.GetString("IdentityResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a IMAP server.
        /// </summary>
        public static string ImapServer {
            get {
                return ResourceManager.GetString("ImapServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Incoming email.
        /// </summary>
        public static string IncomingEmail {
            get {
                return ResourceManager.GetString("IncomingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Inserted data are not valid..
        /// </summary>
        public static string InvalidData {
            get {
                return ResourceManager.GetString("InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Email &apos;{0}&apos; is invalid..
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Role name &apos;{0}&apos; is invalid..
        /// </summary>
        public static string InvalidRoleName {
            get {
                return ResourceManager.GetString("InvalidRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid token..
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a User name &apos;{0}&apos; is invalid, can only contain letters or digits..
        /// </summary>
        public static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} items deleted..
        /// </summary>
        public static string ItemsDeleted {
            get {
                return ResourceManager.GetString("ItemsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Keep me logged in.
        /// </summary>
        public static string Keep_me_logged_in {
            get {
                return ResourceManager.GetString("Keep me logged in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Key.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Loading in progress....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a User is locked out.
        /// </summary>
        public static string LockedUser {
            get {
                return ResourceManager.GetString("LockedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Log in.
        /// </summary>
        public static string Log_in {
            get {
                return ResourceManager.GetString("Log in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a A user with this login already exists..
        /// </summary>
        public static string LoginAlreadyAssociated {
            get {
                return ResourceManager.GetString("LoginAlreadyAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Login Attempt Failed.
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Please login first.
        /// </summary>
        public static string LoginRequired {
            get {
                return ResourceManager.GetString("LoginRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Main settings.
        /// </summary>
        public static string MainSettings {
            get {
                return ResourceManager.GetString("MainSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Multi-tenancy.
        /// </summary>
        public static string MultiTenancy {
            get {
                return ResourceManager.GetString("MultiTenancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New API Resource.
        /// </summary>
        public static string New_API_Resource {
            get {
                return ResourceManager.GetString("New API Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New Client.
        /// </summary>
        public static string New_Client {
            get {
                return ResourceManager.GetString("New Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New Identity Resource.
        /// </summary>
        public static string New_Identity_Resource {
            get {
                return ResourceManager.GetString("New Identity Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New Role.
        /// </summary>
        public static string New_Role {
            get {
                return ResourceManager.GetString("New Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New User.
        /// </summary>
        public static string New_User {
            get {
                return ResourceManager.GetString("New User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New translation.
        /// </summary>
        public static string NewTranslation {
            get {
                return ResourceManager.GetString("NewTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a You are not authorized to perform the operation.
        /// </summary>
        public static string NotAuthorizedTo {
            get {
                return ResourceManager.GetString("NotAuthorizedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a OpenID Clients.
        /// </summary>
        public static string OpenIdClients {
            get {
                return ResourceManager.GetString("OpenIdClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Operation Failed.
        /// </summary>
        public static string Operation_Failed {
            get {
                return ResourceManager.GetString("Operation Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Operation not allowed.
        /// </summary>
        public static string Operation_not_allowed {
            get {
                return ResourceManager.GetString("Operation not allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Operation Successful.
        /// </summary>
        public static string Operation_Successful {
            get {
                return ResourceManager.GetString("Operation Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Outgoing email.
        /// </summary>
        public static string OutgoingEmail {
            get {
                return ResourceManager.GetString("OutgoingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Password Confirmation.
        /// </summary>
        public static string Password_Confirmation {
            get {
                return ResourceManager.GetString("Password Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Password Reset.
        /// </summary>
        public static string Password_Reset {
            get {
                return ResourceManager.GetString("Password Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The password and confirmation password do not match..
        /// </summary>
        public static string PasswordConfirmationFailed {
            get {
                return ResourceManager.GetString("PasswordConfirmationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Incorrect password..
        /// </summary>
        public static string PasswordMismatch {
            get {
                return ResourceManager.GetString("PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Passwords must have at least one digit (&apos;0&apos;-&apos;9&apos;)..
        /// </summary>
        public static string PasswordRequiresDigit {
            get {
                return ResourceManager.GetString("PasswordRequiresDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Passwords must have at least one lowercase (&apos;a&apos;-&apos;z&apos;)..
        /// </summary>
        public static string PasswordRequiresLower {
            get {
                return ResourceManager.GetString("PasswordRequiresLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Passwords must have at least one non alphanumeric character..
        /// </summary>
        public static string PasswordRequiresNonAlphanumeric {
            get {
                return ResourceManager.GetString("PasswordRequiresNonAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Passwords must have at least one uppercase (&apos;A&apos;-&apos;Z&apos;)..
        /// </summary>
        public static string PasswordRequiresUpper {
            get {
                return ResourceManager.GetString("PasswordRequiresUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Passwords must be at least {0} characters..
        /// </summary>
        public static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Permissions.
        /// </summary>
        public static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Permissions list fetched.
        /// </summary>
        public static string Permissions_list_fetched {
            get {
                return ResourceManager.GetString("Permissions list fetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Please wait....
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a POP3 server.
        /// </summary>
        public static string PopServer {
            get {
                return ResourceManager.GetString("PopServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Port.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Read API resources data.
        /// </summary>
        public static string ReadApiResourcePermission {
            get {
                return ResourceManager.GetString("ReadApiResourcePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Read clients data.
        /// </summary>
        public static string ReadClientPermission {
            get {
                return ResourceManager.GetString("ReadClientPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Read identity resources data.
        /// </summary>
        public static string ReadIdentityResourcePermission {
            get {
                return ResourceManager.GetString("ReadIdentityResourcePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Read roles data (permissions, etc.&quot;).
        /// </summary>
        public static string ReadRolePermission {
            get {
                return ResourceManager.GetString("ReadRolePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Read users data (Names, Emails, Phone Numbers, etc.).
        /// </summary>
        public static string ReadUserPermission {
            get {
                return ResourceManager.GetString("ReadUserPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Recovery code.
        /// </summary>
        public static string RecoveryCode {
            get {
                return ResourceManager.GetString("RecoveryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Recovery codes left.
        /// </summary>
        public static string RecoveryCodesLeft {
            get {
                return ResourceManager.GetString("RecoveryCodesLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Registration.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reload translations.
        /// </summary>
        public static string ReloadTranslations {
            get {
                return ResourceManager.GetString("ReloadTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Remember browser.
        /// </summary>
        public static string RememberBrowser {
            get {
                return ResourceManager.GetString("RememberBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reset Password.
        /// </summary>
        public static string Reset_Password {
            get {
                return ResourceManager.GetString("Reset Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reset Authenticator.
        /// </summary>
        public static string ResetAuthenticator {
            get {
                return ResourceManager.GetString("ResetAuthenticator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reset Password Attempt Failed.
        /// </summary>
        public static string ResetPasswordFailed {
            get {
                return ResourceManager.GetString("ResetPasswordFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reset Password Successful.
        /// </summary>
        public static string ResetPasswordSuccessful {
            get {
                return ResourceManager.GetString("ResetPasswordSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Role {0} already exists.
        /// </summary>
        public static string Role__0__already_exists {
            get {
                return ResourceManager.GetString("Role {0} already exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Role {0} cannot be deleted.
        /// </summary>
        public static string Role__0__cannot_be_deleted {
            get {
                return ResourceManager.GetString("Role {0} cannot be deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Role {0} cannot be edited.
        /// </summary>
        public static string Role__0__cannot_be_edited {
            get {
                return ResourceManager.GetString("Role {0} cannot be edited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Role {0} created.
        /// </summary>
        public static string Role__0__created {
            get {
                return ResourceManager.GetString("Role {0} created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Role {0} deleted.
        /// </summary>
        public static string Role__0__deleted {
            get {
                return ResourceManager.GetString("Role {0} deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Role {0} updated.
        /// </summary>
        public static string Role__0__updated {
            get {
                return ResourceManager.GetString("Role {0} updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a This role {0} is still used by a user, you cannot delete it.
        /// </summary>
        public static string RoleInUseWarning {
            get {
                return ResourceManager.GetString("RoleInUseWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Send Confirmation.
        /// </summary>
        public static string Send_Confirmation {
            get {
                return ResourceManager.GetString("Send Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sender email.
        /// </summary>
        public static string SenderEmail {
            get {
                return ResourceManager.GetString("SenderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sender name.
        /// </summary>
        public static string SenderName {
            get {
                return ResourceManager.GetString("SenderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sign in with.
        /// </summary>
        public static string Sign_in_with {
            get {
                return ResourceManager.GetString("Sign in with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sign up.
        /// </summary>
        public static string Sign_up {
            get {
                return ResourceManager.GetString("Sign up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a SMTP server.
        /// </summary>
        public static string SmtpServer {
            get {
                return ResourceManager.GetString("SmtpServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Spaces are not permitted..
        /// </summary>
        public static string SpacesNotPermitted {
            get {
                return ResourceManager.GetString("SpacesNotPermitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tenant.
        /// </summary>
        public static string Tenant {
            get {
                return ResourceManager.GetString("Tenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tenant {0} cannot be deleted.
        /// </summary>
        public static string Tenant__0__cannot_be_deleted {
            get {
                return ResourceManager.GetString("Tenant {0} cannot be deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tenant {0} created.
        /// </summary>
        public static string Tenant__0__created {
            get {
                return ResourceManager.GetString("Tenant {0} created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tenant {0} deleted.
        /// </summary>
        public static string Tenant__0__deleted {
            get {
                return ResourceManager.GetString("Tenant {0} deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tenant {0} updated.
        /// </summary>
        public static string Tenant__0__updated {
            get {
                return ResourceManager.GetString("Tenant {0} updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tenants.
        /// </summary>
        public static string Tenants {
            get {
                return ResourceManager.GetString("Tenants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The API resource {0} doesn&apos;t exist.
        /// </summary>
        public static string The_API_resource__0__doesn_t_exist {
            get {
                return ResourceManager.GetString("The API resource {0} doesn\'t exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The client {0} doesn&apos;t exist.
        /// </summary>
        public static string The_client__0__doesn_t_exist {
            get {
                return ResourceManager.GetString("The client {0} doesn\'t exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The Identity resource {0} doesn&apos;t exist.
        /// </summary>
        public static string The_Identity_resource__0__doesn_t_exist {
            get {
                return ResourceManager.GetString("The Identity resource {0} doesn\'t exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The role {0} doesn&apos;t exist.
        /// </summary>
        public static string The_role__0__doesn_t_exist {
            get {
                return ResourceManager.GetString("The role {0} doesn\'t exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The tenant {0} doesn&apos;t exist.
        /// </summary>
        public static string The_tenant__0__doesn_t_exist {
            get {
                return ResourceManager.GetString("The tenant {0} doesn\'t exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The user {0} doesn&apos;t exist.
        /// </summary>
        public static string The_user__0__doesn_t_exist {
            get {
                return ResourceManager.GetString("The user {0} doesn\'t exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The user doesn&apos;t exist.
        /// </summary>
        public static string The_user_doesn_t_exist {
            get {
                return ResourceManager.GetString("The user doesn\'t exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ToDo List.
        /// </summary>
        public static string TodoNav {
            get {
                return ResourceManager.GetString("TodoNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Translation.
        /// </summary>
        public static string Translation {
            get {
                return ResourceManager.GetString("Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Translations.
        /// </summary>
        public static string Translations {
            get {
                return ResourceManager.GetString("Translations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Two Factor Authentication.
        /// </summary>
        public static string TwoFactorAuthentication {
            get {
                return ResourceManager.GetString("TwoFactorAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unauthorized access.
        /// </summary>
        public static string UnauthorizedAccess {
            get {
                return ResourceManager.GetString("UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Update password.
        /// </summary>
        public static string Update_Password {
            get {
                return ResourceManager.GetString("Update Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Edit existing API resources.
        /// </summary>
        public static string UpdateApiResourcePermission {
            get {
                return ResourceManager.GetString("UpdateApiResourcePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Edit existing clients.
        /// </summary>
        public static string UpdateClientPermission {
            get {
                return ResourceManager.GetString("UpdateClientPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Edit existing identity resource.
        /// </summary>
        public static string UpdateIdentityResourcePermission {
            get {
                return ResourceManager.GetString("UpdateIdentityResourcePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Update Password Failed.
        /// </summary>
        public static string UpdatePasswordFailed {
            get {
                return ResourceManager.GetString("UpdatePasswordFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Update Password Successful.
        /// </summary>
        public static string UpdatePasswordSuccessful {
            get {
                return ResourceManager.GetString("UpdatePasswordSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Edit existing roles.
        /// </summary>
        public static string UpdateRolePermission {
            get {
                return ResourceManager.GetString("UpdateRolePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Edit existing users.
        /// </summary>
        public static string UpdateUserPermission {
            get {
                return ResourceManager.GetString("UpdateUserPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a User {0} created.
        /// </summary>
        public static string User__0__created {
            get {
                return ResourceManager.GetString("User {0} created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a User Profile.
        /// </summary>
        public static string User_Profile {
            get {
                return ResourceManager.GetString("User Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a User already has a password set..
        /// </summary>
        public static string UserAlreadyHasPassword {
            get {
                return ResourceManager.GetString("UserAlreadyHasPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a User already in role &apos;{0}&apos;..
        /// </summary>
        public static string UserAlreadyInRole {
            get {
                return ResourceManager.GetString("UserAlreadyInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a User Creation Failed.
        /// </summary>
        public static string UserCreationFailed {
            get {
                return ResourceManager.GetString("UserCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a User Creation Successful.
        /// </summary>
        public static string UserCreationSuccessful {
            get {
                return ResourceManager.GetString("UserCreationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lockout is not enabled for this user..
        /// </summary>
        public static string UserLockoutNotEnabled {
            get {
                return ResourceManager.GetString("UserLockoutNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a User is not in role &apos;{0}&apos;..
        /// </summary>
        public static string UserNotInRole {
            get {
                return ResourceManager.GetString("UserNotInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Verification Code.
        /// </summary>
        public static string VerificationCode {
            get {
                return ResourceManager.GetString("VerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Verification code is invalid.
        /// </summary>
        public static string VerificationCodeInvalid {
            get {
                return ResourceManager.GetString("VerificationCodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Verify code.
        /// </summary>
        public static string VerifyCode {
            get {
                return ResourceManager.GetString("VerifyCode", resourceCulture);
            }
        }
    }
}
