//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorBoilerplate.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorBoilerplate.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} API resources fetched.
        /// </summary>
        public static string _0__API_resources_fetched {
            get {
                return ResourceManager.GetString("{0} API resources fetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} clients fetched.
        /// </summary>
        public static string _0__clients_fetched {
            get {
                return ResourceManager.GetString("{0} clients fetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} identity resources fetched.
        /// </summary>
        public static string _0__identity_resources_fetched {
            get {
                return ResourceManager.GetString("{0} identity resources fetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} roles fetched.
        /// </summary>
        public static string _0__roles_fetched {
            get {
                return ResourceManager.GetString("{0} roles fetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} tenants fetched.
        /// </summary>
        public static string _0__tenants_fetched {
            get {
                return ResourceManager.GetString("{0} tenants fetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} users fetched.
        /// </summary>
        public static string _0__users_fetched {
            get {
                return ResourceManager.GetString("{0} users fetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow.
        /// </summary>
        public static string Allow {
            get {
                return ResourceManager.GetString("Allow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already registered?.
        /// </summary>
        public static string AlreadyRegistered {
            get {
                return ResourceManager.GetString("AlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Resource {0} created.
        /// </summary>
        public static string API_Resource__0__created {
            get {
                return ResourceManager.GetString("API Resource {0} created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Resource {0} deleted.
        /// </summary>
        public static string API_Resource__0__deleted {
            get {
                return ResourceManager.GetString("API Resource {0} deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Resource {0} updated.
        /// </summary>
        public static string API_Resource__0__updated {
            get {
                return ResourceManager.GetString("API Resource {0} updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenID API resources.
        /// </summary>
        public static string ApiResources {
            get {
                return ResourceManager.GetString("ApiResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api Audit Log.
        /// </summary>
        public static string AppAdminNavApiAuditLog {
            get {
                return ResourceManager.GetString("AppAdminNavApiAuditLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB Logging Viewer.
        /// </summary>
        public static string AppAdminNavDBLoggingView {
            get {
                return ResourceManager.GetString("AppAdminNavDBLoggingView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FrontEnd.
        /// </summary>
        public static string AppAdminNavFrontEnd {
            get {
                return ResourceManager.GetString("AppAdminNavFrontEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring.
        /// </summary>
        public static string AppAdminNavMonitoring {
            get {
                return ResourceManager.GetString("AppAdminNavMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help &amp; Support.
        /// </summary>
        public static string AppHelpAndSupport {
            get {
                return ResourceManager.GetString("AppHelpAndSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string AppHoverAdmin {
            get {
                return ResourceManager.GetString("AppHoverAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize Navigation Bar.
        /// </summary>
        public static string AppHoverNavMinimize {
            get {
                return ResourceManager.GetString("AppHoverNavMinimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Navigation Bar.
        /// </summary>
        public static string AppHoverNavToggle {
            get {
                return ResourceManager.GetString("AppHoverNavToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blazer Boilerplate.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string AppNavDashboard {
            get {
                return ResourceManager.GetString("AppNavDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and Drop.
        /// </summary>
        public static string AppNavDragAndDrop {
            get {
                return ResourceManager.GetString("AppNavDragAndDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string AppNavEmail {
            get {
                return ResourceManager.GetString("AppNavEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string AppNavFeatures {
            get {
                return ResourceManager.GetString("AppNavFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum.
        /// </summary>
        public static string AppNavForum {
            get {
                return ResourceManager.GetString("AppNavForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage.
        /// </summary>
        public static string AppNavHome {
            get {
                return ResourceManager.GetString("AppNavHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Email.
        /// </summary>
        public static string AppNavReadEmail {
            get {
                return ResourceManager.GetString("AppNavReadEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshots.
        /// </summary>
        public static string AppNavScreenshots {
            get {
                return ResourceManager.GetString("AppNavScreenshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Email.
        /// </summary>
        public static string AppNavSendEmail {
            get {
                return ResourceManager.GetString("AppNavSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsors.
        /// </summary>
        public static string AppNavSponsors {
            get {
                return ResourceManager.GetString("AppNavSponsors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlazorBP.
        /// </summary>
        public static string AppShortName {
            get {
                return ResourceManager.GetString("AppShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete &apos;{0}&apos;?.
        /// </summary>
        public static string Are_you_sure_you_want_to_delete__0__ {
            get {
                return ResourceManager.GetString("Are you sure you want to delete {0}?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication required.
        /// </summary>
        public static string AuthenticationRequired {
            get {
                return ResourceManager.GetString("AuthenticationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticator code.
        /// </summary>
        public static string AuthenticatorCode {
            get {
                return ResourceManager.GetString("AuthenticatorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string BreadCrumbadmin {
            get {
                return ResourceManager.GetString("BreadCrumbadmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Audit Log.
        /// </summary>
        public static string BreadCrumbadminapilog {
            get {
                return ResourceManager.GetString("BreadCrumbadminapilog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Resources.
        /// </summary>
        public static string BreadCrumbadminapiResources {
            get {
                return ResourceManager.GetString("BreadCrumbadminapiResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string BreadCrumbadminclients {
            get {
                return ResourceManager.GetString("BreadCrumbadminclients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Log.
        /// </summary>
        public static string BreadCrumbadmindblog {
            get {
                return ResourceManager.GetString("BreadCrumbadmindblog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity Resources.
        /// </summary>
        public static string BreadCrumbadminidentityResources {
            get {
                return ResourceManager.GetString("BreadCrumbadminidentityResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Manager.
        /// </summary>
        public static string BreadCrumbadminmultitenancy {
            get {
                return ResourceManager.GetString("BreadCrumbadminmultitenancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles Manager.
        /// </summary>
        public static string BreadCrumbadminroles {
            get {
                return ResourceManager.GetString("BreadCrumbadminroles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string BreadCrumbadminsettings {
            get {
                return ResourceManager.GetString("BreadCrumbadminsettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Configurations.
        /// </summary>
        public static string BreadCrumbadminsettingsemail {
            get {
                return ResourceManager.GetString("BreadCrumbadminsettingsemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string BreadCrumbadminusers {
            get {
                return ResourceManager.GetString("BreadCrumbadminusers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string BreadCrumbdashboard {
            get {
                return ResourceManager.GetString("BreadCrumbdashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and Drop.
        /// </summary>
        public static string BreadCrumbdrag_and_drop {
            get {
                return ResourceManager.GetString("BreadCrumbdrag_and_drop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Email.
        /// </summary>
        public static string BreadCrumbemail {
            get {
                return ResourceManager.GetString("BreadCrumbemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Email.
        /// </summary>
        public static string BreadCrumbemail_view {
            get {
                return ResourceManager.GetString("BreadCrumbemail_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum.
        /// </summary>
        public static string BreadCrumbforum {
            get {
                return ResourceManager.GetString("BreadCrumbforum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string BreadCrumbHome {
            get {
                return ResourceManager.GetString("BreadCrumbHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshots.
        /// </summary>
        public static string BreadCrumbscreenshots {
            get {
                return ResourceManager.GetString("BreadCrumbscreenshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsors.
        /// </summary>
        public static string BreadCrumbsponsors {
            get {
                return ResourceManager.GetString("BreadCrumbsponsors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToDo.
        /// </summary>
        public static string BreadCrumbtodo_list {
            get {
                return ResourceManager.GetString("BreadCrumbtodo_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser remembered.
        /// </summary>
        public static string BrowserRemembered {
            get {
                return ResourceManager.GetString("BrowserRemembered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string Change_Password {
            get {
                return ResourceManager.GetString("Change Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password for {0}.
        /// </summary>
        public static string Change_password_for__0_ {
            get {
                return ResourceManager.GetString("Change password for {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client {0} created.
        /// </summary>
        public static string Client__0__created {
            get {
                return ResourceManager.GetString("Client {0} created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client {0} deleted.
        /// </summary>
        public static string Client__0__deleted {
            get {
                return ResourceManager.GetString("Client {0} deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client {0} updated.
        /// </summary>
        public static string Client__0__updated {
            get {
                return ResourceManager.GetString("Client {0} updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimistic concurrency failure, object has been modified..
        /// </summary>
        public static string ConcurrencyFailure {
            get {
                return ResourceManager.GetString("ConcurrencyFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        public static string Confirm_Delete {
            get {
                return ResourceManager.GetString("Confirm Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Email.
        /// </summary>
        public static string Confirm_Email {
            get {
                return ResourceManager.GetString("Confirm Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new API resource.
        /// </summary>
        public static string CreateApiResourcePermission {
            get {
                return ResourceManager.GetString("CreateApiResourcePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new client.
        /// </summary>
        public static string CreateClientPermission {
            get {
                return ResourceManager.GetString("CreateClientPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new identity resource.
        /// </summary>
        public static string CreateIdentityResourcePermission {
            get {
                return ResourceManager.GetString("CreateIdentityResourcePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new role.
        /// </summary>
        public static string CreateRolePermission {
            get {
                return ResourceManager.GetString("CreateRolePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new user.
        /// </summary>
        public static string CreateUserPermission {
            get {
                return ResourceManager.GetString("CreateUserPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown failure has occurred..
        /// </summary>
        public static string DefaultError {
            get {
                return ResourceManager.GetString("DefaultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete any API resource.
        /// </summary>
        public static string DeleteApiResourcePermission {
            get {
                return ResourceManager.GetString("DeleteApiResourcePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete any client.
        /// </summary>
        public static string DeleteClientPermission {
            get {
                return ResourceManager.GetString("DeleteClientPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete any identity resource.
        /// </summary>
        public static string DeleteIdentityResourcePermission {
            get {
                return ResourceManager.GetString("DeleteIdentityResourcePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete any role.
        /// </summary>
        public static string DeleteRolePermission {
            get {
                return ResourceManager.GetString("DeleteRolePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete any user.
        /// </summary>
        public static string DeleteUserPermission {
            get {
                return ResourceManager.GetString("DeleteUserPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email &apos;{0}&apos; is already taken..
        /// </summary>
        public static string DuplicateEmail {
            get {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name &apos;{0}&apos; is already taken..
        /// </summary>
        public static string DuplicateRoleName {
            get {
                return ResourceManager.GetString("DuplicateRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name &apos;{0}&apos; is already taken..
        /// </summary>
        public static string DuplicateUserName {
            get {
                return ResourceManager.GetString("DuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit &apos;{0}&apos;.
        /// </summary>
        public static string Edit__0_ {
            get {
                return ResourceManager.GetString("Edit {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is not a valid e-mail address..
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not confirmed.
        /// </summary>
        public static string EmailNotConfirmed {
            get {
                return ResourceManager.GetString("EmailNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email settings.
        /// </summary>
        public static string EmailSettings {
            get {
                return ResourceManager.GetString("EmailSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Verification Failed.
        /// </summary>
        public static string EmailVerificationFailed {
            get {
                return ResourceManager.GetString("EmailVerificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Verification Successful.
        /// </summary>
        public static string EmailVerificationSuccessful {
            get {
                return ResourceManager.GetString("EmailVerificationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} and at max {1} characters long..
        /// </summary>
        public static string ErrorInvalidLength {
            get {
                return ResourceManager.GetString("ErrorInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is mandatory..
        /// </summary>
        public static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string Forgot_your_password_ {
            get {
                return ResourceManager.GetString("Forgot your password?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your authenticator?.
        /// </summary>
        public static string ForgotAuthenticator {
            get {
                return ResourceManager.GetString("ForgotAuthenticator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password Email Sent.
        /// </summary>
        public static string ForgotPasswordEmailSent {
            get {
                return ResourceManager.GetString("ForgotPasswordEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity Resource {0} created.
        /// </summary>
        public static string Identity_Resource__0__created {
            get {
                return ResourceManager.GetString("Identity Resource {0} created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity Resource {0} deleted.
        /// </summary>
        public static string Identity_Resource__0__deleted {
            get {
                return ResourceManager.GetString("Identity Resource {0} deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity Resource {0} updated.
        /// </summary>
        public static string Identity_Resource__0__updated {
            get {
                return ResourceManager.GetString("Identity Resource {0} updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenID Identity Resources.
        /// </summary>
        public static string IdentityResources {
            get {
                return ResourceManager.GetString("IdentityResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMAP server.
        /// </summary>
        public static string ImapServer {
            get {
                return ResourceManager.GetString("ImapServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming email.
        /// </summary>
        public static string IncomingEmail {
            get {
                return ResourceManager.GetString("IncomingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserted data are not valid..
        /// </summary>
        public static string InvalidData {
            get {
                return ResourceManager.GetString("InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email &apos;{0}&apos; is invalid..
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name &apos;{0}&apos; is invalid..
        /// </summary>
        public static string InvalidRoleName {
            get {
                return ResourceManager.GetString("InvalidRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token..
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name &apos;{0}&apos; is invalid, can only contain letters or digits..
        /// </summary>
        public static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} items deleted..
        /// </summary>
        public static string ItemsDeleted {
            get {
                return ResourceManager.GetString("ItemsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep me logged in.
        /// </summary>
        public static string Keep_me_logged_in {
            get {
                return ResourceManager.GetString("Keep me logged in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading in progress....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is locked out.
        /// </summary>
        public static string LockedUser {
            get {
                return ResourceManager.GetString("LockedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Log_in {
            get {
                return ResourceManager.GetString("Log in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user with this login already exists..
        /// </summary>
        public static string LoginAlreadyAssociated {
            get {
                return ResourceManager.GetString("LoginAlreadyAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Attempt Failed.
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login first.
        /// </summary>
        public static string LoginRequired {
            get {
                return ResourceManager.GetString("LoginRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main settings.
        /// </summary>
        public static string MainSettings {
            get {
                return ResourceManager.GetString("MainSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-tenancy.
        /// </summary>
        public static string MultiTenancy {
            get {
                return ResourceManager.GetString("MultiTenancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New API Resource.
        /// </summary>
        public static string New_API_Resource {
            get {
                return ResourceManager.GetString("New API Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Client.
        /// </summary>
        public static string New_Client {
            get {
                return ResourceManager.GetString("New Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Identity Resource.
        /// </summary>
        public static string New_Identity_Resource {
            get {
                return ResourceManager.GetString("New Identity Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Role.
        /// </summary>
        public static string New_Role {
            get {
                return ResourceManager.GetString("New Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User.
        /// </summary>
        public static string New_User {
            get {
                return ResourceManager.GetString("New User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New translation.
        /// </summary>
        public static string NewTranslation {
            get {
                return ResourceManager.GetString("NewTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to perform the operation.
        /// </summary>
        public static string NotAuthorizedTo {
            get {
                return ResourceManager.GetString("NotAuthorizedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenID Clients.
        /// </summary>
        public static string OpenIdClients {
            get {
                return ResourceManager.GetString("OpenIdClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Failed.
        /// </summary>
        public static string Operation_Failed {
            get {
                return ResourceManager.GetString("Operation Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation not allowed.
        /// </summary>
        public static string Operation_not_allowed {
            get {
                return ResourceManager.GetString("Operation not allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Successful.
        /// </summary>
        public static string Operation_Successful {
            get {
                return ResourceManager.GetString("Operation Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outgoing email.
        /// </summary>
        public static string OutgoingEmail {
            get {
                return ResourceManager.GetString("OutgoingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Confirmation.
        /// </summary>
        public static string Password_Confirmation {
            get {
                return ResourceManager.GetString("Password Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Reset.
        /// </summary>
        public static string Password_Reset {
            get {
                return ResourceManager.GetString("Password Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string PasswordConfirmationFailed {
            get {
                return ResourceManager.GetString("PasswordConfirmationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password..
        /// </summary>
        public static string PasswordMismatch {
            get {
                return ResourceManager.GetString("PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must have at least one digit (&apos;0&apos;-&apos;9&apos;)..
        /// </summary>
        public static string PasswordRequiresDigit {
            get {
                return ResourceManager.GetString("PasswordRequiresDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must have at least one lowercase (&apos;a&apos;-&apos;z&apos;)..
        /// </summary>
        public static string PasswordRequiresLower {
            get {
                return ResourceManager.GetString("PasswordRequiresLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must have at least one non alphanumeric character..
        /// </summary>
        public static string PasswordRequiresNonAlphanumeric {
            get {
                return ResourceManager.GetString("PasswordRequiresNonAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must have at least one uppercase (&apos;A&apos;-&apos;Z&apos;)..
        /// </summary>
        public static string PasswordRequiresUpper {
            get {
                return ResourceManager.GetString("PasswordRequiresUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must be at least {0} characters..
        /// </summary>
        public static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions list fetched.
        /// </summary>
        public static string Permissions_list_fetched {
            get {
                return ResourceManager.GetString("Permissions list fetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POP3 server.
        /// </summary>
        public static string PopServer {
            get {
                return ResourceManager.GetString("PopServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read API resources data.
        /// </summary>
        public static string ReadApiResourcePermission {
            get {
                return ResourceManager.GetString("ReadApiResourcePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read clients data.
        /// </summary>
        public static string ReadClientPermission {
            get {
                return ResourceManager.GetString("ReadClientPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read identity resources data.
        /// </summary>
        public static string ReadIdentityResourcePermission {
            get {
                return ResourceManager.GetString("ReadIdentityResourcePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read roles data (permissions, etc.&quot;).
        /// </summary>
        public static string ReadRolePermission {
            get {
                return ResourceManager.GetString("ReadRolePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read users data (Names, Emails, Phone Numbers, etc.).
        /// </summary>
        public static string ReadUserPermission {
            get {
                return ResourceManager.GetString("ReadUserPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery code.
        /// </summary>
        public static string RecoveryCode {
            get {
                return ResourceManager.GetString("RecoveryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery codes left.
        /// </summary>
        public static string RecoveryCodesLeft {
            get {
                return ResourceManager.GetString("RecoveryCodesLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload translations.
        /// </summary>
        public static string ReloadTranslations {
            get {
                return ResourceManager.GetString("ReloadTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember browser.
        /// </summary>
        public static string RememberBrowser {
            get {
                return ResourceManager.GetString("RememberBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string Reset_Password {
            get {
                return ResourceManager.GetString("Reset Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Authenticator.
        /// </summary>
        public static string ResetAuthenticator {
            get {
                return ResourceManager.GetString("ResetAuthenticator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password Attempt Failed.
        /// </summary>
        public static string ResetPasswordFailed {
            get {
                return ResourceManager.GetString("ResetPasswordFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password Successful.
        /// </summary>
        public static string ResetPasswordSuccessful {
            get {
                return ResourceManager.GetString("ResetPasswordSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role {0} already exists.
        /// </summary>
        public static string Role__0__already_exists {
            get {
                return ResourceManager.GetString("Role {0} already exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role {0} cannot be deleted.
        /// </summary>
        public static string Role__0__cannot_be_deleted {
            get {
                return ResourceManager.GetString("Role {0} cannot be deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role {0} cannot be edited.
        /// </summary>
        public static string Role__0__cannot_be_edited {
            get {
                return ResourceManager.GetString("Role {0} cannot be edited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role {0} created.
        /// </summary>
        public static string Role__0__created {
            get {
                return ResourceManager.GetString("Role {0} created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role {0} deleted.
        /// </summary>
        public static string Role__0__deleted {
            get {
                return ResourceManager.GetString("Role {0} deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role {0} updated.
        /// </summary>
        public static string Role__0__updated {
            get {
                return ResourceManager.GetString("Role {0} updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This role {0} is still used by a user, you cannot delete it.
        /// </summary>
        public static string RoleInUseWarning {
            get {
                return ResourceManager.GetString("RoleInUseWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Confirmation.
        /// </summary>
        public static string Send_Confirmation {
            get {
                return ResourceManager.GetString("Send Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender email.
        /// </summary>
        public static string SenderEmail {
            get {
                return ResourceManager.GetString("SenderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender name.
        /// </summary>
        public static string SenderName {
            get {
                return ResourceManager.GetString("SenderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in with.
        /// </summary>
        public static string Sign_in_with {
            get {
                return ResourceManager.GetString("Sign in with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string Sign_up {
            get {
                return ResourceManager.GetString("Sign up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP server.
        /// </summary>
        public static string SmtpServer {
            get {
                return ResourceManager.GetString("SmtpServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spaces are not permitted..
        /// </summary>
        public static string SpacesNotPermitted {
            get {
                return ResourceManager.GetString("SpacesNotPermitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant.
        /// </summary>
        public static string Tenant {
            get {
                return ResourceManager.GetString("Tenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant {0} cannot be deleted.
        /// </summary>
        public static string Tenant__0__cannot_be_deleted {
            get {
                return ResourceManager.GetString("Tenant {0} cannot be deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant {0} created.
        /// </summary>
        public static string Tenant__0__created {
            get {
                return ResourceManager.GetString("Tenant {0} created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant {0} deleted.
        /// </summary>
        public static string Tenant__0__deleted {
            get {
                return ResourceManager.GetString("Tenant {0} deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant {0} updated.
        /// </summary>
        public static string Tenant__0__updated {
            get {
                return ResourceManager.GetString("Tenant {0} updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenants.
        /// </summary>
        public static string Tenants {
            get {
                return ResourceManager.GetString("Tenants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The API resource {0} doesn&apos;t exist.
        /// </summary>
        public static string The_API_resource__0__doesn_t_exist {
            get {
                return ResourceManager.GetString("The API resource {0} doesn\'t exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client {0} doesn&apos;t exist.
        /// </summary>
        public static string The_client__0__doesn_t_exist {
            get {
                return ResourceManager.GetString("The client {0} doesn\'t exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Identity resource {0} doesn&apos;t exist.
        /// </summary>
        public static string The_Identity_resource__0__doesn_t_exist {
            get {
                return ResourceManager.GetString("The Identity resource {0} doesn\'t exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The role {0} doesn&apos;t exist.
        /// </summary>
        public static string The_role__0__doesn_t_exist {
            get {
                return ResourceManager.GetString("The role {0} doesn\'t exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tenant {0} doesn&apos;t exist.
        /// </summary>
        public static string The_tenant__0__doesn_t_exist {
            get {
                return ResourceManager.GetString("The tenant {0} doesn\'t exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user {0} doesn&apos;t exist.
        /// </summary>
        public static string The_user__0__doesn_t_exist {
            get {
                return ResourceManager.GetString("The user {0} doesn\'t exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user doesn&apos;t exist.
        /// </summary>
        public static string The_user_doesn_t_exist {
            get {
                return ResourceManager.GetString("The user doesn\'t exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToDo List.
        /// </summary>
        public static string TodoNav {
            get {
                return ResourceManager.GetString("TodoNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation.
        /// </summary>
        public static string Translation {
            get {
                return ResourceManager.GetString("Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations.
        /// </summary>
        public static string Translations {
            get {
                return ResourceManager.GetString("Translations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Factor Authentication.
        /// </summary>
        public static string TwoFactorAuthentication {
            get {
                return ResourceManager.GetString("TwoFactorAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized access.
        /// </summary>
        public static string UnauthorizedAccess {
            get {
                return ResourceManager.GetString("UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update password.
        /// </summary>
        public static string Update_Password {
            get {
                return ResourceManager.GetString("Update Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit existing API resources.
        /// </summary>
        public static string UpdateApiResourcePermission {
            get {
                return ResourceManager.GetString("UpdateApiResourcePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit existing clients.
        /// </summary>
        public static string UpdateClientPermission {
            get {
                return ResourceManager.GetString("UpdateClientPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit existing identity resource.
        /// </summary>
        public static string UpdateIdentityResourcePermission {
            get {
                return ResourceManager.GetString("UpdateIdentityResourcePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Password Failed.
        /// </summary>
        public static string UpdatePasswordFailed {
            get {
                return ResourceManager.GetString("UpdatePasswordFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Password Successful.
        /// </summary>
        public static string UpdatePasswordSuccessful {
            get {
                return ResourceManager.GetString("UpdatePasswordSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit existing roles.
        /// </summary>
        public static string UpdateRolePermission {
            get {
                return ResourceManager.GetString("UpdateRolePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit existing users.
        /// </summary>
        public static string UpdateUserPermission {
            get {
                return ResourceManager.GetString("UpdateUserPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} created.
        /// </summary>
        public static string User__0__created {
            get {
                return ResourceManager.GetString("User {0} created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Profile.
        /// </summary>
        public static string User_Profile {
            get {
                return ResourceManager.GetString("User Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already has a password set..
        /// </summary>
        public static string UserAlreadyHasPassword {
            get {
                return ResourceManager.GetString("UserAlreadyHasPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already in role &apos;{0}&apos;..
        /// </summary>
        public static string UserAlreadyInRole {
            get {
                return ResourceManager.GetString("UserAlreadyInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Creation Failed.
        /// </summary>
        public static string UserCreationFailed {
            get {
                return ResourceManager.GetString("UserCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Creation Successful.
        /// </summary>
        public static string UserCreationSuccessful {
            get {
                return ResourceManager.GetString("UserCreationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lockout is not enabled for this user..
        /// </summary>
        public static string UserLockoutNotEnabled {
            get {
                return ResourceManager.GetString("UserLockoutNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not in role &apos;{0}&apos;..
        /// </summary>
        public static string UserNotInRole {
            get {
                return ResourceManager.GetString("UserNotInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Code.
        /// </summary>
        public static string VerificationCode {
            get {
                return ResourceManager.GetString("VerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code is invalid.
        /// </summary>
        public static string VerificationCodeInvalid {
            get {
                return ResourceManager.GetString("VerificationCodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify code.
        /// </summary>
        public static string VerifyCode {
            get {
                return ResourceManager.GetString("VerifyCode", resourceCulture);
            }
        }
    }
}
