//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorBoilerplate.Localization {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorBoilerplate.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Create a new API resource.
        /// </summary>
        public static string CreateApiResourcePermission {
            get {
                return ResourceManager.GetString("CreateApiResourcePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Create a new client.
        /// </summary>
        public static string CreateClientPermission {
            get {
                return ResourceManager.GetString("CreateClientPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Create a new identity resource.
        /// </summary>
        public static string CreateIdentityResourcePermission {
            get {
                return ResourceManager.GetString("CreateIdentityResourcePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Create a new role.
        /// </summary>
        public static string CreateRolePermission {
            get {
                return ResourceManager.GetString("CreateRolePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Create a new user.
        /// </summary>
        public static string CreateUserPermission {
            get {
                return ResourceManager.GetString("CreateUserPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delete any API resource.
        /// </summary>
        public static string DeleteApiResourcePermission {
            get {
                return ResourceManager.GetString("DeleteApiResourcePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delete any client.
        /// </summary>
        public static string DeleteClientPermission {
            get {
                return ResourceManager.GetString("DeleteClientPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delete any identity resource.
        /// </summary>
        public static string DeleteIdentityResourcePermission {
            get {
                return ResourceManager.GetString("DeleteIdentityResourcePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delete any role.
        /// </summary>
        public static string DeleteRolePermission {
            get {
                return ResourceManager.GetString("DeleteRolePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delete any user.
        /// </summary>
        public static string DeleteUserPermission {
            get {
                return ResourceManager.GetString("DeleteUserPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Read API resources data.
        /// </summary>
        public static string ReadApiResourcePermission {
            get {
                return ResourceManager.GetString("ReadApiResourcePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Read clients data.
        /// </summary>
        public static string ReadClientPermission {
            get {
                return ResourceManager.GetString("ReadClientPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Read identity resources data.
        /// </summary>
        public static string ReadIdentityResourcePermission {
            get {
                return ResourceManager.GetString("ReadIdentityResourcePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Read roles data (permissions, etc.&quot;).
        /// </summary>
        public static string ReadRolePermission {
            get {
                return ResourceManager.GetString("ReadRolePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Read users data (Names, Emails, Phone Numbers, etc.).
        /// </summary>
        public static string ReadUserPermission {
            get {
                return ResourceManager.GetString("ReadUserPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Edit existing API resources.
        /// </summary>
        public static string UpdateApiResourcePermission {
            get {
                return ResourceManager.GetString("UpdateApiResourcePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Edit existing clients.
        /// </summary>
        public static string UpdateClientPermission {
            get {
                return ResourceManager.GetString("UpdateClientPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Edit existing identity resource.
        /// </summary>
        public static string UpdateIdentityResourcePermission {
            get {
                return ResourceManager.GetString("UpdateIdentityResourcePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Edit existing roles.
        /// </summary>
        public static string UpdateRolePermission {
            get {
                return ResourceManager.GetString("UpdateRolePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Edit existing users.
        /// </summary>
        public static string UpdateUserPermission {
            get {
                return ResourceManager.GetString("UpdateUserPermission", resourceCulture);
            }
        }
    }
}
