apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omamldata-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: managed-nfs-storage