//Autogenerated from Permissions.tt
using System.ComponentModel.DataAnnotations;

namespace BlazorBoilerplate.Infrastructure.Storage.Permissions
{
    public static class Permissions
    {
        #region Admin
        public static class User
        {
            [Display(Name = "CreateUserPermission")]
            public const string Create = "User.Create";
            [Display(Name = "UpdateUserPermission")]
            public const string Update = "User.Update";
            [Display(Name = "ReadUserPermission")]
            public const string Read = "User.Read";
            [Display(Name = "DeleteUserPermission")]
            public const string Delete = "User.Delete";
        }
        public static class Role
        {
            [Display(Name = "CreateRolePermission")]
            public const string Create = "Role.Create";
            [Display(Name = "UpdateRolePermission")]
            public const string Update = "Role.Update";
            [Display(Name = "ReadRolePermission")]
            public const string Read = "Role.Read";
            [Display(Name = "DeleteRolePermission")]
            public const string Delete = "Role.Delete";
        }
        public static class Client
        {
            [Display(Name = "CreateClientPermission")]
            public const string Create = "Client.Create";
            [Display(Name = "UpdateClientPermission")]
            public const string Update = "Client.Update";
            [Display(Name = "ReadClientPermission")]
            public const string Read = "Client.Read";
            [Display(Name = "DeleteClientPermission")]
            public const string Delete = "Client.Delete";
        }
        public static class ApiResource
        {
            [Display(Name = "CreateApiResourcePermission")]
            public const string Create = "ApiResource.Create";
            [Display(Name = "UpdateApiResourcePermission")]
            public const string Update = "ApiResource.Update";
            [Display(Name = "ReadApiResourcePermission")]
            public const string Read = "ApiResource.Read";
            [Display(Name = "DeleteApiResourcePermission")]
            public const string Delete = "ApiResource.Delete";
        }
        public static class IdentityResource
        {
            [Display(Name = "CreateIdentityResourcePermission")]
            public const string Create = "IdentityResource.Create";
            [Display(Name = "UpdateIdentityResourcePermission")]
            public const string Update = "IdentityResource.Update";
            [Display(Name = "ReadIdentityResourcePermission")]
            public const string Read = "IdentityResource.Read";
            [Display(Name = "DeleteIdentityResourcePermission")]
            public const string Delete = "IdentityResource.Delete";
        }
        public static class Tenant
        {
            [Display(Name = "CreateTenantPermission")]
            public const string Create = "Tenant.Create";
            [Display(Name = "UpdateTenantPermission")]
            public const string Update = "Tenant.Update";
            [Display(Name = "ReadTenantPermission")]
            public const string Read = "Tenant.Read";
            [Display(Name = "DeleteTenantPermission")]
            public const string Delete = "Tenant.Delete";
        }
        #endregion
    }
}